### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-ailight

### ISSUE THREAD

**Issue by Supersimo88** [stelgenhof/homebridge-ailight#1]
[2/25/2018, 9:13:07 AM] ====================
[2/25/2018, 9:13:08 AM] ERROR LOADING PLUGIN homebridge-ailight:
[2/25/2018, 9:13:08 AM] Error: Plugin /usr/local/lib/node_modules/homebridge-ailight requires a HomeBridge version of 0.4.28 which does not satisfy the current HomeBridge version of 0.4.38. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:142:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:138:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[2/25/2018, 9:13:08 AM] ====================

**Comment by stelgenhof** [comment]
Thank you for reporting this. It says you have Homebridge 0.4.38 installed whereas this plugin only supports up 0.4.28.

**Comment by Supersimo88** [comment]
I saw the error, I wanted to know if it was possible to update the plugin to be compatible with the latest version of homebridge, thanks

**Comment by stelgenhof** [comment]
I haven't tested it myself yet, however you can try with 0.4.38 by changing the version number in the package.json file. I will do some testing first and then release a new update (may take some days) :)

**Comment by Supersimo88** [comment]
[2018-2-25 12:15:16] Plugin /usr/local/lib/node_modules/homebridge-ailight requires Node version of 6.11.3 which does not satisfy the current Node version of v8.2.1. You may need to upgrade your installation of Node.
[2018-2-25 12:15:22] Loaded plugin: homebridge-ailight
[2018-2-25 12:15:22] Registering accessory 'homebridge-ailight.AiLight'
[2018-2-25 12:15:22] ---
[2018-2-25 12:15:22] Loaded config.json with 1 accessories and 0 platforms.
[2018-2-25 12:15:22] ---
[2018-2-25 12:15:22] Loading 0 platforms...
[2018-2-25 12:15:22] Loading 1 accessories...
[2018-2-25 12:15:22] [Bedroom Light] Initializing AiLight accessory...
Setup Payload:
X-HM://0023ISYWYPP9C
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                             
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2018-2-25 12:15:24] Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-ailight/index.js:132
        this.log('Error getting State (statuscode %s): %s', response.statusCode, error);
                                                                    ^

TypeError: Cannot read property 'statusCode' of undefined
    at AiLightAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-ailight/index.js:132:69)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ailight/index.js:47:7)
    at self.callback (/usr/local/lib/node_modules/homebridge-ailight/node_modules/request/request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-ailight/node_modules/request/request.js:878:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)

**Comment by stelgenhof** [comment]
This message could be the result of Homebridge not being able to communicate to your light bulb. Are you sure your light bulb is working properly and you can control it via the UI, REST API or MQTT?

**Comment by Supersimo88** [comment]
Yes, i can control the light via ui and mqtt
I've found the error, was in the config.json, my fault.

**Comment by stelgenhof** [comment]
Ok. Good to hear! So it works now?

**Comment by Supersimo88** [comment]
It works for on off, but it does not seem that the color change has any effect if not to set all the LEDs to 255

**Comment by stelgenhof** [comment]
Hmm, I need to check it myself. Haven't used it for a while.

**Comment by stelgenhof** [comment]
I've updated this package to use Homebridge v0.4.38. You can update it by simply executing the following statement: `npm install -g homebridge-ailight`.
