### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by 88adong88** [stelgenhof/homebridge-ailight#2]
[5/19/2018, 1:18:14 PM] Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'.
[5/19/2018, 1:18:14 PM] Plugin /usr/lib/node_modules/homebridge-ailight requires Node version of 6.11.3 which does not satisfy the current Node version of v7.1.0. You may need to upgrade your installation of Node.
[5/19/2018, 1:18:16 PM] Loaded plugin: homebridge-ailight
[5/19/2018, 1:18:16 PM] Registering accessory 'homebridge-ailight.AiLight'
[5/19/2018, 1:18:16 PM] ---
[5/19/2018, 1:18:16 PM] Loaded plugin: homebridge-mqtt-blinds
[5/19/2018, 1:18:16 PM] Registering accessory 'homebridge-mqtt-blinds.BlindsMQTT'
[5/19/2018, 1:18:16 PM] ---
[5/19/2018, 1:18:17 PM] Loaded plugin: homebridge-mqtt-dimmer
[5/19/2018, 1:18:17 PM] Registering accessory 'homebridge-mqtt-dimmer.mqtt-dimmer'
[5/19/2018, 1:18:17 PM] ---
[5/19/2018, 1:18:18 PM] Loaded plugin: homebridge-mqtt-door
[5/19/2018, 1:18:18 PM] Registering accessory 'homebridge-mqtt-door.mqtt-door'
[5/19/2018, 1:18:18 PM] ---
[5/19/2018, 1:18:18 PM] Loaded plugin: homebridge-mqttgaragedoor
[5/19/2018, 1:18:18 PM] Registering accessory 'homebridge-mqttgarage.Mqttgarage'
[5/19/2018, 1:18:18 PM] ---
[5/19/2018, 1:18:19 PM] Loaded plugin: homebridge-mqttlightbulb
[5/19/2018, 1:18:19 PM] Registering accessory 'homebridge-mqttlightbulb.mqttlightbulb'
[5/19/2018, 1:18:19 PM] ---
[5/19/2018, 1:18:19 PM] Loaded config.json with 4 accessories and 0 platforms.
[5/19/2018, 1:18:19 PM] ---
[5/19/2018, 1:18:19 PM] Loading 0 platforms...
[5/19/2018, 1:18:19 PM] Loading 4 accessories...
[5/19/2018, 1:18:19 PM] [Building Door] Initializing mqtt-door accessory...
[5/19/2018, 1:18:19 PM] [Garage?ppnare] Initializing Mqttgarage accessory...
[5/19/2018, 1:18:19 PM] [Bedroom Light] Initializing AiLight accessory...
[5/19/2018, 1:18:19 PM] [crome] Initializing Mqttgarage accessory...
Setup Payload:
X-HM://0024XUS27J3NI
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 888-89-999 │
    └────────────┘

[5/19/2018, 1:18:20 PM] Homebridge is running on port 51826.
[5/19/2018, 1:18:36 PM] [crome] getDoorPosition
[5/19/2018, 1:18:36 PM] [crome] getObstructionDetected
[5/19/2018, 1:18:36 PM] [crome] getDoorTargetPosition
[5/19/2018, 1:18:36 PM] [Garage?ppnare] getObstructionDetected
[5/19/2018, 1:18:36 PM] [Garage?ppnare] getDoorPosition
[5/19/2018, 1:18:36 PM] [Garage?ppnare] getDoorTargetPosition
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AiLightAccessory.<anonymous> (/usr/lib/node_modules/homebridge-ailight/index.js:226:25)
    at Request._callback (/usr/lib/node_modules/homebridge-ailight/index.js:47:7)
    at Request.self.callback (/usr/lib/node_modules/homebridge-ailight/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ailight/node_modules/request/request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-ailight/node_modules/request/request.js:1079:12)

**Comment by 88adong88** [comment]
homebridge v0.4.42

**Comment by stelgenhof** [comment]
Thank you for sharing. This is likely related to the fact you're using a more newer version of homebridge. I'll have a look and update the package.

**Comment by stelgenhof** [comment]
@88adong88 I've updated the Homebridge version (0.4.42).

**Comment by stelgenhof** [comment]
New package v0.1.3 is available on NPMJS.
